apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webdemo
  name: webdemo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webdemo
    spec:
      containers:
      - image: nksingh0/task:4
        name: webdemo
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: webdemo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3333
    nodePort: 30001
  selector:
    app: webdemo
